@host = http://127.0.0.1:9090

###
POST {{host}}/auth/login HTTP/1.1
Content-Type: "application/json"

{"username":"aaa","password":"111"}

###
GET {{host}}/home HTTP/1.1

###
GET {{host}}/hi HTTP/1.1

###
GET {{host}}/p1 HTTP/1.1

###
GET {{host}}/p2 HTTP/1.1